version: '3'
name: nacos
services:
  nacos-2.3:
    container_name: nacos-2.3
    image: nacos/nacos-server:v2.3.0
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./software/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
    #restart: on-failure

