logLevel := Level.Info

resolvers += Resolver.bintrayIvyRepo("2m", "sbt-plugins")

addSbtPlugin("com.lightbend.paradox" % "sbt-paradox" % "0.10.6")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox-theme" % "0.10.6")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.10.0")
addSbtPlugin("com.github.sbt" % "sbt-paradox-material-theme" % "0.7.0")
addSbtPlugin("com.github.sbt" % "sbt-site" % "1.5.0")
addSbtPlugin("com.github.sbt" % "sbt-ghpages" % "0.8.0")
addSbtPlugin("com.github.sbt" % "sbt-javaagent" % "0.1.8")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.2.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.10.0")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
//addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.11")
//addSbtPlugin("com.typesafe.sbt" % "sbt-multi-jvm" % "0.6.0")
//addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
// addSbtPlugin("com.dwijnand" % "sbt-dynver" % "5.0.1")
// addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")
